server:
  port: 8080
spring:
  application:
    name: greeting-service
  config:
    import:
    - optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: prod
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
        #- 'refresh'
        #- 'env'
        #- 'beans'
        # https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
        
# commented due spring config server        
#greeting-service:
#  greeting : "Olá"
#  default-value : "mundo - seu lindo!"
  